//! Synthetic IRIs generated by the serializer.

pub const SYNTH_LITERAL: &str = "_literal";

pub const SYNTH_LOCAL_LITERAL: &str = "_localliteral";

pub const SYNTH_LOCAL_THING: &str = "_localthing";

pub const SYNTH_THING: &str = "_thing";

pub const SYNTH_LITERAL_VALUE: &str = "_value";
